### ISSUE TITLE
wrong breadcrumb and title at examination_boards

### ISSUE THREAD

**Issue by lucasgeron** [MarczalTSIGP/SGTCC#186]
At **examination_boards**, when the **type** is: _Project_, the breadcrumb and title display TCC 2.
Project is part of TCC1. 

![](https://media.discordapp.net/attachments/1053331369004126310/1120712761052254288/image.png?width=913&height=416)
![](https://media.discordapp.net/attachments/1053331369004126310/1120712761245179914/image.png?width=913&height=453)

**Comment by MarczalTSIGP** [comment]
Fixed.
