### ISSUE TITLE
feat: After create a calendar activity redirect to list calendars page.

### ISSUE THREAD

**Issue by MarczalTSIGP** [MarczalTSIGP/SGTCC#202]
Change task name from:
feat: After create a calendar activity redirect to list calendars page.
to 
feat: After edit a calendar activity redirect to activities list calendars page

**Comment by camilaesouza** [comment]
Ao rodar os teste para validação da tarefa, gerou alguns erros de classes que não se relacionam com a tarefa:

Failures:

  1) Document::sign #sign when signs the signature of the term of commitment signs the document of the term of commitment
     Failure/Error: expect(page).to have_content('Entre com seu RA e senha para assinar o documento.')
       expected to find text "Entre com seu RA e senha para assinar o documento." in "Francisca da Mota\nemail44@email.com\nACADÊMICO\nPágina inicial\nCalendários\nReuniões\nBancas de defesa\nDOCUMENTOS\nPara assinar\nAssinados\nPágina inicial\nVisualizar documento\nVisualizar documento\nMinistério da Educação\nUniversidade Tecnológica Federal do Paraná\nCâmpus Guarapuava\nCurso Superior de Tecnologia em Sistemas para Internet\nTERMO DE COMPROMISSO DE ORIENTAÇÃO DE TRABALHO DE CONCLUSÃO DE CURSO\nEu, abbr189 Professor 95, professora desta instituição, declaro para os devidos fins, estar de acordo em assumir a orientação do trabalho de conclusão de curso do acadêmico Francisca da Mota, RA 1159423.\nTema:\nOdio optio ut.\nCoorientador da UTFPR:\nabbr191 Professor 96\nCoorientador externo:\nabbr192 External member 96\nTCC desenvolvido em parceria com a instituição:\nNome fantasia: secured line\nResponsável: External member 95\nGuarapuava, 11 de Setembro de 2023.\nAssinar documento\nEste documento será assinado eletronicamente.\nAssinar documento\nSalvar documento em PDF\nEste documento será salvo no formato PDF.\nSalvar em PDF\nEsse termo deve ser assinado pelos seguintes usuários:\nUSUÁRIO ASSINOU\nFrancisca da Mota - Acadêmica não\nProfessor 95 - Orientadora não\nProfessor 96 - Coorientador da UTFPR não\nExternal member 96 - Coorientador externo não\nVoltar"
     # ./spec/features/academics/documents/term_of_commitment/documents_sign_spec.rb:17:in `block (4 levels) in <main>'

  2) Document::sign #sign when the password is wrong shows alert message
     Failure/Error: fill_in 'login_confirmation', with: external_member.email
     
     Capybara::ElementNotFound:
       Unable to find field "login_confirmation" that is not disabled
     # ./spec/features/external_members/documents/term_of_commitment/documents_sign_spec.rb:37:in `block (4 levels) in <main>'

  3) Document::sign #sign when signs the signature of the term of commitment signs the document of the term of commitment
     Failure/Error: fill_in 'login_confirmation', with: professor.username
     
     Capybara::ElementNotFound:
       Unable to find field "login_confirmation" that is not disabled
     # ./spec/features/professors/documents/term_of_commitment/documents_sign_spec.rb:17:in `block (4 levels) in <main>'

Finished in 18 minutes 9 seconds (files took 3.62 seconds to load)
825 examples, 3 failures

Failed examples:

rspec ./spec/features/academics/documents/term_of_commitment/documents_sign_spec.rb:15 # Document::sign #sign when signs the signature of the term of commitment signs the document of the term of commitment
rspec ./spec/features/external_members/documents/term_of_commitment/documents_sign_spec.rb:35 # Document::sign #sign when the password is wrong shows alert message
rspec ./spec/features/professors/documents/term_of_commitment/documents_sign_spec.rb:15 # Document::sign #sign when signs the signature of the term of commitment signs the document of the term of commitment

**Comment by MarczalTSIGP** [comment]
**Proposal Solution Presentation**
- [x] Tell about the problem/task. 
- [x] Demonstrated the problem at the application.
- [x] Talked about the modification.
- [x] Talked about the tests.

**Comments**

The task was with wrong title

**Comment by MarczalTSIGP** [comment]
@camilaesouza looks like intermittent tests, Document.first, may not return the right document, let's try this:

File: spec/features/academics/documents/term_of_commitment/documents_sign_spec.rb
Change line 10 to `visit academics_document_path(orientation.tco)`

File: ./spec/features/external_members/documents/term_of_commitment/documents_sign_spec.rb 
Change line 12 to `visit external_members_document_path(orientation.tco)`

File: ./spec/features/professors/documents/term_of_commitment/documents_sign_spec.rb
Change line 10 to `visit professors_document_path(orientation.tco)`

Let me know if worked.

**Comment by MarczalTSIGP** [comment]
Presentation: 
- OK

Research:
- A route responsible_calendar_activities_path works with no params.
