### ISSUE TITLE
fix: Not allow remove examination boards after the minutes are generated

### ISSUE THREAD

**Issue by MarczalTSIGP** [MarczalTSIGP/SGTCC#217]

**Comment by MarczalTSIGP** [comment]
# Proposals

- [x] Problem explained
- [x] Talked about the Changes
- [ ] Talked about the Tests
- [ ] Slides

# Comments
- Hide trash icon
- Not accept the Request.

**Comment by pedrosezar** [comment]
When uploading my branch, I created the pull request and in testing it returned the following error
![erro-pull-request-sprint-2](https://github.com/MarczalTSIGP/SGTCC/assets/58284302/ad349590-6ae3-4241-84a8-0cedde3b1a1f)
