### ISSUE TITLE
fix: adjust the number of meetings and add captions about orientations status

### ISSUE THREAD

**Issue by MarczalTSIGP** [MarczalTSIGP/SGTCC#262]

**Comment by amandaacarolyne** [comment]
-> Na tela inicial mostra uma quantidade total de reuniões e na tela de reuniões mostra outra quantidade total.

-> Na lista de bancas de defesa, inclua uma legenda para os símbolos de status representados por círculos amarelos e brancos. TAMBÉM NA DE ORIENTAÇÃO

**Comment by MarczalTSIGP** [comment]
**Proposal Solution Presentation**
- [x] Tell about the problem/task. 
- [x] Demonstrated the problem at the application.
- [x] Talked about the modification.
- [x] Talked about the tests.

**Comments**
- Take care about test all the areas that the total of meeting is displayed

**Comment by MarczalTSIGP** [comment]
**Solution Presentation**
- [x] Tell about the problem/task. 
- [x] Demonstrated the problem at the application.
- [x] Talked about the modification.
- [x] Talked about the tests.

**Comments**
-  OK
